<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251202221400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(30) NOT NULL, middle_name VARCHAR(30) DEFAULT NULL, last_name VARCHAR(30) DEFAULT NULL, gender VARCHAR(255) NOT NULL, nisn VARCHAR(10) NOT NULL, nis VARCHAR(5) NOT NULL, birth_place VARCHAR(50) DEFAULT NULL, birth_date DATE DEFAULT NULL, religion VARCHAR(255) NOT NULL, address TEXT DEFAULT NULL, father_name VARCHAR(50) DEFAULT NULL, mother_name VARCHAR(50) DEFAULT NULL, mobile VARCHAR(15) DEFAULT NULL, parent_mobile VARCHAR(15) DEFAULT NULL, email VARCHAR(30) DEFAULT NULL, parent_email VARCHAR(50) DEFAULT NULL, father_job VARCHAR(100) DEFAULT NULL, mother_job VARCHAR(100) DEFAULT NULL, parent_income VARCHAR(20) DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B723AF339D86650F ON student (user_id_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(20) NOT NULL, last_name VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF339D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF339D86650F');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE "user"');
    }
}
